#!/bin/bash

# Fix ownership and permissions of custon GNUPGHOME dir.

if [ ! -d "$GNUPGHOME" ]; then
    mkdir "$GNUPGHOME"
    chown -R "$(whoami)" "$GNUPGHOME"/
    find "$GNUPGHOME" -type f -exec chmod 600 {} \;
    find "$GNUPGHOME" -type d -exec chmod 700 {} \;
fi
