#!/bin/bash

# # Fix ownership and permissions of custon GNUPGHOME dir.
# GNUPGHOME="~/.config/gnupg"
# if [ ! -d "$GNUPGHOME" ]; then
#     mkdir -p "$GNUPGHOME"
#     chown -R "$(whoami)" "$GNUPGHOME"/
#     find "$GNUPGHOME" -type f -exec chmod 600 {} \;
#     find "$GNUPGHOME" -type d -exec chmod 700 {} \;
# fi

[ "$(command -v virtualbox)" ]          && sudo usermod -aG vboxusers "$(whoami)"
[ "$(command -v docker)" ]              && sudo usermod -aG docker "$(whoami)"
sudo systemctl enable --now libvirtd    && sudo usermod -aG libvirt "$(whoami)"

# sudo chmod 700 ~/.ssh
# sudo chmod 644 ~/.ssh/key.pub
# sudo chmod 600 ~/.ssh/key
