---
packages:
  - bat
  - lsd
  - fontawesome-fonts-web
  - google-carlito-fonts
  - hddtemp
  - htop
  - lm_sensors
  - lshw
  - mediainfo
  - nvme-cli
  - openssh
  - p7zip
  - procinfo
  - procs
  - pv
  - smartmontools
  - package: util-linux-user
    purpose: Provides `chsh` to change to zsh
  - yt-dlp
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting
