---
pre_install:
  run:
    - >
      grep 'fastestmirror=1' /etc/dnf/dnf.conf ||
      echo 'fastestmirror=1' |
      sudo tee -a /etc/dnf/dnf.conf

    - >
      grep 'max_parallel_downloads=10' /etc/dnf/dnf.conf ||
      echo 'max_parallel_downloads=10' |
      sudo tee -a /etc/dnf/dnf.conf

    - >
      grep 'defaultyes=True' /etc/dnf/dnf.conf ||
      echo 'defaultyes=True' |
      sudo tee -a /etc/dnf/dnf.conf
